//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spell_Editor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArmorTable
    {
        public int ArmorId { get; set; }
        public string ArmorName { get; set; }
        public int GeneralArmor { get; set; }
        public int BulletArmor { get; set; }
        public bool Degrade { get; set; }
        public bool RangedDefense { get; set; }
        public bool Supernatural { get; set; }
        public int BonusHealth { get; set; }
        public int BonusDefense { get; set; }
    }
}
