//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spell_Editor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artifact_Table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Artifact_Table()
        {
            this.ArtifactAttainments = new HashSet<ArtifactAttainment>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public short Reach { get; set; }
        public string Description { get; set; }
        public short Mana { get; set; }
        public string Path { get; set; }
        public short Cost { get; set; }
        public short Gnosis { get; set; }
        public Nullable<int> CharacterId { get; set; }
        public bool ImperialSurcharge { get; set; }
        public bool YantraBonus { get; set; }
    
        public virtual Character_List Character_List { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArtifactAttainment> ArtifactAttainments { get; set; }
    }
}
