//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spell_Editor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArtifactAttainment
    {
        public int Id { get; set; }
        public int AttainmentId { get; set; }
        public int ArtifactId { get; set; }
    
        public virtual Artifact_Table Artifact_Table { get; set; }
        public virtual Attainment_Table Attainment_Table { get; set; }
    }
}
