//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spell_Editor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attainment_Table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Attainment_Table()
        {
            this.ArtifactAttainments = new HashSet<ArtifactAttainment>();
        }
    
        public int Id { get; set; }
        public string attainment_name { get; set; }
        public string attainment_arcana { get; set; }
        public short attainment_level { get; set; }
        public string description { get; set; }
        public bool ItemUsable { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArtifactAttainment> ArtifactAttainments { get; set; }
    }
}
