//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spell_Editor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ceremony
    {
        public int CeremonyId { get; set; }
        public string Name { get; set; }
        public string Requirement { get; set; }
        public string Subject { get; set; }
        public string Duration { get; set; }
        public string Symbols { get; set; }
        public string Ritual { get; set; }
        public string Success { get; set; }
        public string DiePool { get; set; }
        public int Cost { get; set; }
    }
}
