//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spell_Editor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImbuedItemSpell
    {
        public int ImbuedItemSpellId { get; set; }
        public int ImbuedItemId { get; set; }
        public int SpellId { get; set; }
    
        public virtual Imbued_Table Imbued_Table { get; set; }
        public virtual Spell_Table Spell_Table { get; set; }
    }
}
