//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spell_Editor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Imbued_Table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Imbued_Table()
        {
            this.ImbuedItemSpells = new HashSet<ImbuedItemSpell>();
            this.ItemEnhancements = new HashSet<ItemEnhancement>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public short Spell_Level { get; set; }
        public Nullable<short> Battery_Dots { get; set; }
        public string Description { get; set; }
        public Nullable<int> CharacterID { get; set; }
        public short Mana { get; set; }
        public Nullable<int> CurrentCharge { get; set; }
        public short Cost { get; set; }
    
        public virtual Character_List Character_List { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImbuedItemSpell> ImbuedItemSpells { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemEnhancement> ItemEnhancements { get; set; }
    }
}
