//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spell_Editor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemEnhancement
    {
        public int Id { get; set; }
        public Nullable<int> ImbuedItemId { get; set; }
        public Nullable<int> EnhancedItemId { get; set; }
        public Nullable<int> EnhancementId { get; set; }
        public string Enhancement { get; set; }
        public int EnhancementCost { get; set; }
        public Nullable<int> SpellId { get; set; }
    
        public virtual Imbued_Table Imbued_Table { get; set; }
        public virtual RefEnhancement RefEnhancement { get; set; }
        public virtual Spell_Table Spell_Table { get; set; }
    }
}
