//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spell_Editor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MageCaucusInfo
    {
        public int MageCaucusId { get; set; }
        public int MageOrder { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
    
        public virtual MageOrder MageOrder1 { get; set; }
    }
}
