//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spell_Editor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MageConsiliumTitle
    {
        public int ConsiliumTitleId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<bool> SmallEssential { get; set; }
        public Nullable<bool> MediumEssential { get; set; }
        public Nullable<bool> LargeEssential { get; set; }
        public Nullable<bool> UniqueTitle { get; set; }
        public Nullable<int> MaxNumber { get; set; }
        public Nullable<int> MinGnosis { get; set; }
    }
}
