//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spell_Editor.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MonsterEntities : DbContext
    {
        public MonsterEntities()
            : base("name=MonsterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DreadPower> DreadPowers { get; set; }
        public virtual DbSet<Manifestation> Manifestations { get; set; }
        public virtual DbSet<Numina> Numinas { get; set; }
        public virtual DbSet<Essence_Shaping> Essence_Shaping { get; set; }
    }
}
