//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spell_Editor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefLegacy
    {
        public int LegacyId { get; set; }
        public Nullable<int> PathId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> SecondOrderId { get; set; }
        public int RulingArcana { get; set; }
        public Nullable<int> SecondaryArcana { get; set; }
        public string LegacyName { get; set; }
        public string Description { get; set; }
        public bool LeftHanded { get; set; }
    
        public virtual Arcana_Table Arcana_Table { get; set; }
        public virtual Arcana_Table Arcana_Table1 { get; set; }
        public virtual MageOrder MageOrder { get; set; }
        public virtual MageOrder MageOrder1 { get; set; }
        public virtual MagePath MagePath { get; set; }
    }
}
