//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spell_Editor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefShadowGift
    {
        public int RefGiftsId { get; set; }
        public int CategoryId { get; set; }
        public string GiftName { get; set; }
        public Nullable<int> RenownId { get; set; }
        public string Cost { get; set; }
        public string DiePool { get; set; }
        public string Action { get; set; }
        public string Description { get; set; }
        public string Duration { get; set; }
        public string DramaticFailure { get; set; }
        public string Failure { get; set; }
        public string Success { get; set; }
        public string ExceptionalSuccess { get; set; }
    
        public virtual RefRenown RefRenown { get; set; }
        public virtual RefShadowGiftCategory RefShadowGiftCategory { get; set; }
    }
}
