//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spell_Editor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rote_Table
    {
        public int ID { get; set; }
        public int GrimoireID { get; set; }
        public int SpellTableID { get; set; }
        public int SkillID { get; set; }
    
        public virtual Grimoire_Table Grimoire_Table { get; set; }
        public virtual Spell_Table Spell_Table { get; set; }
        public virtual Skill Skill { get; set; }
    }
}
