//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spell_Editor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spell_Table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Spell_Table()
        {
            this.ImbuedItemSpells = new HashSet<ImbuedItemSpell>();
            this.Spell_Arcana_Table = new HashSet<Spell_Arcana_Table>();
            this.Rote_Table = new HashSet<Rote_Table>();
            this.ItemEnhancements = new HashSet<ItemEnhancement>();
        }
    
        public string Spell_Name { get; set; }
        public string Description { get; set; }
        public int Id { get; set; }
        public string PrimaryFactor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImbuedItemSpell> ImbuedItemSpells { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spell_Arcana_Table> Spell_Arcana_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rote_Table> Rote_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemEnhancement> ItemEnhancements { get; set; }
    }
}
