//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spell_Editor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spell_Arcana_Table
    {
        public int Id { get; set; }
        public int Spell_Table_ID { get; set; }
        public string Arcana { get; set; }
        public byte Level { get; set; }
    
        public virtual Spell_Table Spell_Table { get; set; }
    }
}
