//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spell_Editor.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WerewolfEntities : DbContext
    {
        public WerewolfEntities()
            : base("name=WerewolfEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<RefMoonGift> RefMoonGifts { get; set; }
        public virtual DbSet<RefRenown> RefRenowns { get; set; }
        public virtual DbSet<RefShadowGiftCategory> RefShadowGiftCategories { get; set; }
        public virtual DbSet<RefShadowGift> RefShadowGifts { get; set; }
        public virtual DbSet<RefMoonGiftFacet> RefMoonGiftFacets { get; set; }
        public virtual DbSet<Rite> Rites { get; set; }
        public virtual DbSet<FetishTable> FetishTables { get; set; }
    }
}
